#include "constants.h"
//RUNTIME CONST:
chart CONSTANTS::ACT_CREATE_ROOM = "CREATE_ROOM";
chart CONSTANTS::ACT_CREATE_USER = "CREATE_USER";
chart CONSTANTS::ACT_DELETE_ROOM = "DELETE_ROOM";
chart CONSTANTS::ACT_DELETE_USER = "DELETE_USER";
chart CONSTANTS::ACT_DISCONNECT = "DISCONNECT";
chart CONSTANTS::ACT_EARLIER_MESS = "EARLIER_MESS";
chart CONSTANTS::ACT_GET_USERS = "GET_USERS";
chart CONSTANTS::ACT_JOIN_ROOM = "JOIN_ROOM";
chart CONSTANTS::ACT_LOGIN = "LOGIN";
chart CONSTANTS::ACT_ROOM_LIST = "ROOM_LIST";
chart CONSTANTS::ACT_SEND_PRIVATE_MESSAGE = "SEND_PRIVMESSAGE";
chart CONSTANTS::ACT_SEND_PUBLIC_MESSAGE = "SEND_PUBLMESSAGE";
chart CONSTANTS::ACT_SYSTEM = "ACT_SYS";

// Map Parameters
chart CONSTANTS::LF_ACTION = "ACTION";
chart CONSTANTS::LF_INITIATOR = "INITIATOR";
chart CONSTANTS::LF_LAST_MSG = "LF_LAST_MSG";
chart CONSTANTS::LF_LOGIN = "LOGIN";
chart CONSTANTS::LF_PRIVATE_MESSAGE = "PRIVATE_MESSAGE";
chart CONSTANTS::LF_PUBLIC_MESSAGE = "PUBLIC_MESSAGE";
chart CONSTANTS::LF_NAME = "NAME";
chart CONSTANTS::LF_PASSWORD = "PASSWORD";
chart CONSTANTS::LF_REASON = "REASON";
chart CONSTANTS::LF_RESULT = "RESULT";
chart CONSTANTS::LF_ROOMLIST = "ROOMLIST";
chart CONSTANTS::LF_ROOMNAME = "ROOMNAME";
chart CONSTANTS::LF_TOKEN = "TOKEN";
chart CONSTANTS::LF_USERS = "USERS";
chart CONSTANTS::LF_USER_RECIEVER = "USER_RECIEVER";
chart CONSTANTS::LF_USER_TO_DELETE = "USER_TO_DELETE";

chart CONSTANTS::RF_ERROR = "ERROR";
chart CONSTANTS::RF_SUCCESS = "SUCCESS";

//
chart CONSTANTS::RF_ERR_INITIATOR_SERVER = "INITIATOR_SERVER";
chart CONSTANTS::RF_ERR_INITIATOR_CHATROOM = "INITIATOR_CLENT";
chart CONSTANTS::RF_ERR_PERMISSION_DENIDED = "YOUR TOKEN INCORRECT. PERMISSION DENIDED";

chart CONSTANTS::LF_DIRECTION = "DIRECTION";
chart CONSTANTS::RF_DIRECTION_SERVER = "DIRECTION_SERVER";
chart CONSTANTS::RF_DIRECTION_CHATROOM = "DIRECTION_CHATROOM";

chart CONSTANTS::UNKNOWN = "UNKNOWN";

const char CONSTANTS::SERIAL_SYM = '\0';


const std::map<str_type, ACTIONS> _NAME_ACTION = {
    {CONSTANTS::ACT_CREATE_ROOM, ACTIONS::CREATE_ROOM},
    {CONSTANTS::ACT_CREATE_USER, ACTIONS::CREATE_USER},
    {CONSTANTS::ACT_DELETE_ROOM, ACTIONS::DELETE_ROOM},
    {CONSTANTS::ACT_DELETE_USER, ACTIONS::DELETE_USER},
    {CONSTANTS::ACT_DISCONNECT, ACTIONS::DISCONNECT},
    {CONSTANTS::ACT_EARLIER_MESS, ACTIONS::EARLIER_MESSAGES},
    {CONSTANTS::ACT_GET_USERS, ACTIONS::GET_ROOM_USERS},
    {CONSTANTS::ACT_JOIN_ROOM, ACTIONS::JOIN_ROOM},
    {CONSTANTS::ACT_LOGIN, ACTIONS::LOGIN},
    {CONSTANTS::ACT_ROOM_LIST, ACTIONS::GET_ROOMS_LIST},
    {CONSTANTS::ACT_SEND_PRIVATE_MESSAGE, ACTIONS::PRIVATE_MESSAGE},
    {CONSTANTS::ACT_SEND_PUBLIC_MESSAGE, ACTIONS::PUBLIC_MESSAGE},
    {CONSTANTS::ACT_SYSTEM , ACTIONS::SYSTEM}

};
const std::map<ACTIONS, str_type> _ACTION_NAME = {
    {ACTIONS::CREATE_ROOM, CONSTANTS::ACT_CREATE_ROOM},
    {ACTIONS::CREATE_USER,CONSTANTS::ACT_CREATE_USER},
    {ACTIONS::DELETE_ROOM,CONSTANTS::ACT_DELETE_ROOM},
    {ACTIONS::DELETE_USER,CONSTANTS::ACT_DELETE_USER},
    {ACTIONS::DISCONNECT,CONSTANTS::ACT_DISCONNECT},
    {ACTIONS::EARLIER_MESSAGES,CONSTANTS::ACT_EARLIER_MESS},
    {ACTIONS::GET_ROOM_USERS,CONSTANTS::ACT_GET_USERS},
    {ACTIONS::JOIN_ROOM, CONSTANTS::ACT_JOIN_ROOM},
    {ACTIONS::LOGIN,CONSTANTS::ACT_LOGIN},
    {ACTIONS::GET_ROOMS_LIST ,CONSTANTS::ACT_ROOM_LIST},
    {ACTIONS::PRIVATE_MESSAGE, CONSTANTS::ACT_SEND_PRIVATE_MESSAGE},
    {ACTIONS::PUBLIC_MESSAGE,CONSTANTS::ACT_SEND_PUBLIC_MESSAGE},
    {ACTIONS::SYSTEM,CONSTANTS::ACT_SYSTEM}
};

const std::set<str_type> _ACT_SERVER = {
     CONSTANTS::ACT_CREATE_ROOM,
     CONSTANTS::ACT_CREATE_USER,
     CONSTANTS::ACT_DELETE_ROOM,
     CONSTANTS::ACT_DELETE_USER,
     CONSTANTS::ACT_GET_USERS,
     CONSTANTS::ACT_JOIN_ROOM,
     CONSTANTS::ACT_LOGIN,
     CONSTANTS::ACT_ROOM_LIST,
     CONSTANTS::ACT_SEND_PUBLIC_MESSAGE ,
     CONSTANTS::ACT_SEND_PRIVATE_MESSAGE,
     CONSTANTS::ACT_DISCONNECT
};


chart CONSTANTS::ROLE_MASTER = "ROLE_MASTER";
chart CONSTANTS::ROLE_ADMINISTRATOR = "ROLE_ADMINISTRATOR";
chart CONSTANTS::ROLE_SUPERUSER = "ROLE_SUPERUSER";
chart CONSTANTS::ROLE_USER = "ROLE_USER";


const std::map<str_type, Role> _NAME_ROLE = {
    {CONSTANTS::ROLE_ADMINISTRATOR , Role::ADMIN},
    {CONSTANTS::ROLE_MASTER , Role::MASTER},
    {CONSTANTS::ROLE_SUPERUSER , Role::SUPERUSER},
    {CONSTANTS::ROLE_USER , Role::USER}
};

const std::map<Role, str_type> _ROLE_NAME = {
    {Role::ADMIN , CONSTANTS::ROLE_ADMINISTRATOR},
    {Role::MASTER , CONSTANTS::ROLE_MASTER},
    {Role::SUPERUSER , CONSTANTS::ROLE_SUPERUSER},
    {Role::USER , CONSTANTS::ROLE_USER}
};


