#include"constants.h"

const std::map<str_type, ADMIN_ACTIONS> _NAME_ADMIN_ACTION = {
    {CONSTANTS::ADMIN_ACT_BAN_USER, ADMIN_ACTIONS::BAN_USER},
    {CONSTANTS::ADMIN_ACT_CREATE_ROOM, ADMIN_ACTIONS::CREATE_ROOM},
    {CONSTANTS::ADMIN_ACT_DELETE_ROOM, ADMIN_ACTIONS::DELETE_ROOM},
    {CONSTANTS::ADMIN_ACT_DELETE_USER , ADMIN_ACTIONS::DELETE_USER},
    {CONSTANTS::ADMIN_ACT_UNBAN_USER, ADMIN_ACTIONS::UNBAN_USER},
    {CONSTANTS::ADMIN_ACT_SYSTEM , ADMIN_ACTIONS::SYSTEM},
    {CONSTANTS::ADMIN_ACT_UPDATE_ROLE , ADMIN_ACTIONS::UPDATE_ROLE},
    {CONSTANTS::ADMIN_ACT_USER_LIST ,ADMIN_ACTIONS::USER_LIST},
    {CONSTANTS::ADMIN_ACT_ROOM_LIST,ADMIN_ACTIONS::ROOM_LIST},
    {CONSTANTS::ADMIN_ACT_USERLIST_PREDICATE, ADMIN_ACTIONS::USERLIST_PREDICATE}
};
const std::map<ADMIN_ACTIONS, str_type> _ACTION_ADMIN_NAME = {
    {ADMIN_ACTIONS::BAN_USER , CONSTANTS::ADMIN_ACT_BAN_USER},
    {ADMIN_ACTIONS::CREATE_ROOM,CONSTANTS::ADMIN_ACT_CREATE_ROOM},
    {ADMIN_ACTIONS::DELETE_ROOM, CONSTANTS::ADMIN_ACT_DELETE_ROOM},
    {ADMIN_ACTIONS::DELETE_USER, CONSTANTS::ADMIN_ACT_DELETE_USER},
    {ADMIN_ACTIONS::UNBAN_USER , CONSTANTS::ADMIN_ACT_UNBAN_USER},
    {ADMIN_ACTIONS::SYSTEM, CONSTANTS::ADMIN_ACT_SYSTEM},
    {ADMIN_ACTIONS::UPDATE_ROLE, CONSTANTS::ADMIN_ACT_UPDATE_ROLE},
    {ADMIN_ACTIONS::USER_LIST,CONSTANTS::ADMIN_ACT_USER_LIST },
    {ADMIN_ACTIONS::ROOM_LIST, CONSTANTS::ADMIN_ACT_ROOM_LIST},
    {ADMIN_ACTIONS::USERLIST_PREDICATE , CONSTANTS::ADMIN_ACT_USERLIST_PREDICATE}
};
const std::set<str_type> _ACT_ADMIN = {
    CONSTANTS::ADMIN_ACT_BAN_USER, CONSTANTS::ADMIN_ACT_CREATE_ROOM,
    CONSTANTS::ADMIN_ACT_DELETE_USER, CONSTANTS::ADMIN_ACT_DELETE_ROOM,
    CONSTANTS::ADMIN_ACT_SYSTEM, CONSTANTS::ADMIN_ACT_UNBAN_USER,
    CONSTANTS::ADMIN_ACT_UPDATE_ROLE, CONSTANTS::ADMIN_ACT_FIND_USERS,
    CONSTANTS::ADMIN_ACT_USER_LIST, CONSTANTS::ADMIN_ACT_ROOM_LIST,
    CONSTANTS::ADMIN_ACT_USERLIST_PREDICATE
};

//admins const
chart CONSTANTS::ADMIN_ACT_BAN_USER = "ADMIN_BAN_USER";
chart CONSTANTS::ADMIN_ACT_CREATE_ROOM = "ADMIN_CREATE_ROOM";
chart CONSTANTS::ADMIN_ACT_DELETE_USER = "ADMIN_DELETE_USER";
chart CONSTANTS::ADMIN_ACT_DELETE_ROOM = "ADMIN_DELETE_ROOM";
chart CONSTANTS::ADMIN_ACT_FIND_USERS = "ADMIN_FIND_USERS";
chart CONSTANTS::ADMIN_ACT_USER_LIST = "ADMIN_USER_LIST";
chart CONSTANTS::ADMIN_ACT_SYSTEM = "ADMIN_ACT_SYSTEM";
chart CONSTANTS::ADMIN_ACT_UNBAN_USER = "ADMIN_UNBAN_USER";
chart CONSTANTS::ADMIN_ACT_UPDATE_ROLE = "ADMIN_UPDATE_ROLE";
chart CONSTANTS::ADMIN_ACT_USERLIST_PREDICATE = "ADMIN_USERLIST_PREDICATE" ;
chart CONSTANTS::ADMIN_ACT_ROOM_LIST = "ADMIN_ROOM_LIST";
