#include"constants.h"

const std::map<str_type, ADMIN_ACTIONS> _NAME_ADMIN_ACTION = {
    {CONSTANTS::ADMIN_ACT_BAN_USER, ADMIN_ACTIONS::BAN_USER},
    {CONSTANTS::ADMIN_ACT_CREATE_ROOM, ADMIN_ACTIONS::CREATE_ROOM},
    {CONSTANTS::ADMIN_ACT_DELETE_ROOM, ADMIN_ACTIONS::DELETE_ROOM},
    {CONSTANTS::ADMIN_ACT_DELETE_USER , ADMIN_ACTIONS::DELETE_USER},
    {CONSTANTS::ADMIN_ACT_UNBAN_USER, ADMIN_ACTIONS::UNBAN_USER},
    {CONSTANTS::ADMIN_ACT_SYSTEM , ADMIN_ACTIONS::SYSTEM},
    {CONSTANTS::ADMIN_ACT_UPDATE_ROLE , ADMIN_ACTIONS::UPDATE_ROLE},
    {CONSTANTS::ADMIN_ACT_FIND_USERS, ADMIN_ACTIONS::FIND_USERS}
};
const std::map<ADMIN_ACTIONS, str_type> _ACTION_ADMIN_NAME = {
    {ADMIN_ACTIONS::BAN_USER , CONSTANTS::ADMIN_ACT_BAN_USER},
    {ADMIN_ACTIONS::CREATE_ROOM,CONSTANTS::ADMIN_ACT_CREATE_ROOM},
    {ADMIN_ACTIONS::DELETE_ROOM, CONSTANTS::ADMIN_ACT_DELETE_ROOM},
    {ADMIN_ACTIONS::DELETE_USER, CONSTANTS::ADMIN_ACT_DELETE_USER},
    {ADMIN_ACTIONS::SYSTEM, CONSTANTS::ADMIN_ACT_SYSTEM},
    {ADMIN_ACTIONS::UNBAN_USER , CONSTANTS::ADMIN_ACT_UNBAN_USER},
    {ADMIN_ACTIONS::UPDATE_ROLE, CONSTANTS::ADMIN_ACT_UPDATE_ROLE},
    {ADMIN_ACTIONS::FIND_USERS, CONSTANTS::ADMIN_ACT_FIND_USERS}

};
const std::set<str_type> _ACT_ADMIN = {
    CONSTANTS::ADMIN_ACT_BAN_USER, CONSTANTS::ADMIN_ACT_CREATE_ROOM,
    CONSTANTS::ADMIN_ACT_DELETE_USER, CONSTANTS::ADMIN_ACT_DELETE_ROOM,
    CONSTANTS::ADMIN_ACT_SYSTEM, CONSTANTS::ADMIN_ACT_UNBAN_USER,
    CONSTANTS::ADMIN_ACT_UPDATE_ROLE, CONSTANTS::ADMIN_ACT_FIND_USERS
};

//admins const
chart CONSTANTS::ADMIN_ACT_BAN_USER = "BAN_USER";
chart CONSTANTS::ADMIN_ACT_CREATE_ROOM = "CREATE_ROOM";
chart CONSTANTS::ADMIN_ACT_DELETE_USER = "DELETE_USER";
chart CONSTANTS::ADMIN_ACT_DELETE_ROOM = "DELETE_ROOM";
chart CONSTANTS::ADMIN_ACT_FIND_USERS = "FIND_USERS";
chart CONSTANTS::ADMIN_ACT_SYSTEM = "ACT_SYSTEM";
chart CONSTANTS::ADMIN_ACT_UNBAN_USER = "UNBAN_USER";
chart CONSTANTS::ADMIN_ACT_UPDATE_ROLE = "UPDATE_ROLE";
