#include "constants.h"
chart CONSTANTS::ACT_CREATE_ROOM = "CREATE_ROOM";
chart CONSTANTS::ACT_CREATE_USER = "CREATE_USER";
chart CONSTANTS::ACT_DELETE_ROOM = "DELETE_ROOM";
chart CONSTANTS::ACT_DELETE_USER = "DELETE_USER";
chart CONSTANTS::ACT_DISCONNECT = "DISCONNECT";
chart CONSTANTS::ACT_EARLIER_MESS = "EARLIER_MESS";
chart CONSTANTS::ACT_GET_USERS = "GET_USERS";
chart CONSTANTS::ACT_LOGIN = "LOGIN";
chart CONSTANTS::ACT_ROOM_LIST = "ROOM_LIST";
chart CONSTANTS::ACT_SEND_PRIVATE_MESSAGE = "SEND_PRIVMESSAGE";
chart CONSTANTS::ACT_SEND_PUBLIC_MESSAGE = "SEND_PUBLMESSAGE";
chart CONSTANTS::ACT_USER_MESSAGE = "ACT_USER_MESSAGE";

// Map Parameters
chart CONSTANTS::LF_ACTION = "ACTION";
chart CONSTANTS::LF_INITIATOR = "INITIATOR";
chart CONSTANTS::LF_LAST_MSG = "LF_LAST_MSG";
chart CONSTANTS::LF_LOGIN = "LOGIN";
chart CONSTANTS::LF_PRIVATE_MESSAGE = "PRIVATE_MESSAGE";
chart CONSTANTS::LF_PUBLIC_MESSAGE = "PUBLIC_MESSAGE";
chart CONSTANTS::LF_NAME = "NAME";
chart CONSTANTS::LF_PASSWORD = "PASSWORD";
chart CONSTANTS::LF_REASON = "REASON";
chart CONSTANTS::LF_RESULT = "RESULT";
chart CONSTANTS::LF_ROOMLIST = "ROOMLIST";
chart CONSTANTS::LF_ROOMNAME = "ROOMNAME";
chart CONSTANTS::LF_TOKEN = "TOKEN";
chart CONSTANTS::LF_USERS = "USERS";
chart CONSTANTS::LF_USER_RECIEVER = "USER_RECIEVER";
chart CONSTANTS::LF_USER_TO_DELETE = "USER_TO_DELETE";

chart CONSTANTS::RF_ERROR = "ERROR";
chart CONSTANTS::RF_SUCCESS = "SUCCESS";

//
chart CONSTANTS::RF_ERR_INITIATOR_SERVER = "INITIATOR_SERVER";
chart CONSTANTS::RF_ERR_INITIATOR_CHATROOM = "INITIATOR_CLENT";
chart CONSTANTS::RF_ERR_PERMISSION_DENIDED = "YOUR TOKEN INCORRECT. PERMISSION DENIDED";

chart CONSTANTS::LF_DIRECTION = "DIRECTION";
chart CONSTANTS::RF_DIRECTION_SERVER = "DIRECTION_SERVER";
chart CONSTANTS::RF_DIRECTION_CHATROOM = "DIRECTION_CHATROOM";

chart CONSTANTS::CHATROOMS = "DEFAULT_CHATROOMS";
chart CONSTANTS::DB_PASSORD = "DB_PASSORD";
chart CONSTANTS::DB_TABLE_NAME = "DB_TABLE_NAME";
chart CONSTANTS::DB_USER = "DB_USER";
chart CONSTANTS::IP = "IP";
chart CONSTANTS::MAX_CONNECTIONS = "MAX_CONNECTIONS";
chart CONSTANTS::PORT = "PORT";
chart CONSTANTS::UNKNOWN = "UNKNOWN";

const size_t CONSTANTS::N_TOKEN_LEN = 32;
const size_t CONSTANTS::N_MAX_MESSAGE_LEN = 512;
const char CONSTANTS::SERIAL_SYM = '\0';


const std::unordered_map<chart, ACTIONS> _NAME_ACTION = {
    {"ACT_CREATE_ROOM", ACTIONS::CREATE_ROOM},
    {"ACT_CREATE_USER", ACTIONS::CREATE_USER},
    {"ACT_DELETE_ROOM", ACTIONS::DELETE_ROOM},
    {"ACT_DELETE_USER", ACTIONS::DELETE_USER},
    {"ACT_DISCONNECT", ACTIONS::DISCONNECT},
    {"ACT_EARLIER_MESS", ACTIONS::EARLIER_MESSAGES},
    {"ACT_GET_USERS", ACTIONS::GET_ROOM_USERS},
    {"ACT_LOGIN", ACTIONS::LOGIN},
    {"ACT_ROOM_LIST", ACTIONS::GET_ROOMS_LIST},
    {"ACT_SEND_PRIVATE_MESSAGE", ACTIONS::PRIVATE_MESSAGE},
    {"ACT_SEND_PUBLIC_MESSAGE", ACTIONS::PUBLIC_MESSAGE}

};
const std::unordered_map<ACTIONS, chart> _ACTION_NAME = {
    {ACTIONS::CREATE_ROOM,"ACT_CREATE_ROOM"},
    {ACTIONS::CREATE_USER,"ACT_CREATE_USER"},
    {ACTIONS::DELETE_ROOM,"ACT_DELETE_ROOM"},
    {ACTIONS::DELETE_USER,"ACT_DELETE_USER"},
    {ACTIONS::DISCONNECT,"ACT_DISCONNECT"},
    {ACTIONS::EARLIER_MESSAGES,"ACT_EARLIER_MESS"},
    {ACTIONS::GET_ROOM_USERS,"ACT_GET_USERS"},
    {ACTIONS::LOGIN,"ACT_LOGIN"},
    {ACTIONS::GET_ROOMS_LIST ,"ACT_ROOM_LIST"},
    {ACTIONS::PRIVATE_MESSAGE,"ACT_SEND_PRIVATE_MESSAGE"},
    {ACTIONS::PUBLIC_MESSAGE,"ACT_SEND_PUBLIC_MESSAGE"}
};

