#include "constants_load.h"
//C
chart LOAD_CONSTANTS::DEFAULT_CHATROOMS = "DEFAULT_CHATROOMS";
//D
chart LOAD_CONSTANTS::DB_HOST ="DB_HOST";
chart LOAD_CONSTANTS::DB_PASSWORD = "DB_PASSWORD";
chart LOAD_CONSTANTS::DB_PORT = "DB_PORT";
chart LOAD_CONSTANTS::DB_TABLE_NAME = "DB_TABLE_NAME";
chart LOAD_CONSTANTS::DB_USER = "DB_USER";
//M
chart LOAD_CONSTANTS::MAX_CONNECTIONS = "MAX_CONNECTIONS";
chart LOAD_CONSTANTS::MAX_MESSAGE_LEN = "MAX_MESSAGE_LEN" ;
//S
chart LOAD_CONSTANTS::SERVER_IP = "IP_SERVER";
chart LOAD_CONSTANTS::SERVER_PORT = "SERVER_PORT";


////////////////////////////////////////////////////////////////

